version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: business-backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - appnet

  frontend:
    build:
      context: ./frontend
    container_name: business-frontend
    command: npm start
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge